sudo: required
dist: trusty

env:
  global:
    - CLI_VERSION=1.0.0-rc3-004530
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
    - NUGET_XMLDOC_MODE=skip

branches:
  only:
    - master

addons:
  apt:
    packages:
    - gettext
    - libcurl4-openssl-dev
    - libicu-dev
    - libssl-dev
    - libunwind8

install:
  - export DOTNET_INSTALL_DIR="$PWD/.dotnetcli"
  - ./tools/install.sh --version "$CLI_VERSION" --install-dir "$DOTNET_INSTALL_DIR"
  - export PATH="$DOTNET_INSTALL_DIR:$PATH"
  - npm install -g bower
  - npm install -g gulp

script:
  - ./build.sh
