<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Description>Unit and integration tests for https://martincostello.com/</Description>
    <NoWarn>$(NoWarn);CA2000</NoWarn>
    <OutputType>Exe</OutputType>
    <PreserveCompilationContext>true</PreserveCompilationContext>
    <RootNamespace>MartinCostello.Website</RootNamespace>
    <TargetFramework>net11.0</TargetFramework>
    <UseDefaultCodeAnalysisRuleSet>true</UseDefaultCodeAnalysisRuleSet>
    <UseLocalDevelopmentCertificate>true</UseLocalDevelopmentCertificate>
  </PropertyGroup>
  <ItemGroup>
    <AssemblyMetadata Include="DevCertificateFileName" Value="$([System.IO.Path]::GetFileName('$(LocalDevelopmentCertificatePath)'))" />
    <AssemblyMetadata Include="DevCertificatePassword" Value="$(LocalDevelopmentCertificatePassword)" />
    <Compile Include="..\Website.Tests.Shared\**\*.cs" Link="%(Link)" />
    <Content Include="testsettings.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Website\Website.csproj" />
  </ItemGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="GitHubActionsTestLogger" />
    <PackageReference Include="MartinCostello.Logging.XUnit.v3" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="Microsoft.Playwright" />
    <PackageReference Include="Microsoft.Testing.Extensions.CodeCoverage" />
    <PackageReference Include="Shouldly" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="xunit.v3.mtp-v2" />
  </ItemGroup>
  <PropertyGroup>
    <CollectCoverage>true</CollectCoverage>
    <CoverageRunSettings>$(MSBuildThisFileDirectory)tests.runsettings</CoverageRunSettings>
    <Threshold>85,50</Threshold>
  </PropertyGroup>
</Project>
