name: component-detection

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  # TODO Remove once tested
  pull_request:
    branches: [ main ]

permissions: {}

jobs:
  dependency-submission:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    permissions:
      contents: write
      id-token: write

    steps:

      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          filter: 'tree:0'
          show-progress: false

      - name: Run Component Detection
        uses: advanced-security/component-detection-dependency-submission-action@1874d0f72d77ddf201936b16a90f28b237709753 # v0.0.6
