name: dependency-review

on:
  pull_request:

permissions: {}

jobs:
  dependency-review:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:

      - name: Harden runner
        uses: step-security/harden-runner@8d3c67de8e2fe68ef647c8db1e6a09f647780f40 # v2.19.0
        with:
          egress-policy: audit

      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          filter: 'tree:0'
          persist-credentials: false
          show-progress: false

      - name: Review dependencies
        uses: actions/dependency-review-action@2031cfc080254a8a887f58cffee85186f0e49e48 # v4.9.0
