name: lighthouse

on:
  pull_request:
    branches:
      - main
      - dotnet-vnext
      - dotnet-nightly
  workflow_dispatch:

permissions:
  contents: read

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_NOLOGO: true
  DOTNET_SYSTEM_CONSOLE_ALLOW_ANSI_COLOR_REDIRECTION: 1
  NUGET_XMLDOC_MODE: skip
  TERM: xterm

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:

    - name: Checkout code
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        filter: 'tree:0'
        show-progress: false

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@67a3573c9a986a3f9c594539f4ab511d57bb3ce9 # v4.3.1

    - name: Start website
      shell: pwsh
      run: |
        Push-Location (Join-Path "src" "Website")
        npm ci
        npm run build
        Pop-Location
        Start-Process nohup 'dotnet run --project ./src/Website/Website.csproj --configuration Release /p:EnableNETAnalyzers=false /p:EnforceCodeStyleInBuild=false'
        $StatusCode = 0
        $Attempts = 0
        While ($Attempts -lt 20) {
          $Response = Try {
            Invoke-WebRequest "https://localhost:5001" -SkipCertificateCheck
          } catch {
            $_.Exception.Response
          }
          $StatusCode = $Response.StatusCode
          If ($StatusCode -eq 200) {
            break
          }
          $Attempts++
          Start-Sleep -Seconds 5
        }
        If ($StatusCode -ne 200) {
          throw "Failed to successfully connect to website after $Attempts attempts."
        }
        New-Item -Path "${env:GITHUB_WORKSPACE}/artifacts/lighthouse" -ItemType Directory | Out-Null

    - name: Lighthouse
      uses: foo-software/lighthouse-check-action@a80267da2e0244b8a2e457a8575fc47590615852 # v12.0.1
      id: lighthouse
      with:
        device: 'all'
        gitHubAccessToken: ${{ secrets.LIGHTHOUSE_ACCESS_TOKEN }}
        outputDirectory: ${{ github.workspace }}/artifacts/lighthouse
        overridesJsonFile: ./.github/lighthouse.config.json
        prCommentEnabled: true
        urls: 'https://localhost:5001'
        wait: true

    - name: Check Lighthouse scores
      uses: foo-software/lighthouse-check-status-action@2b9d5101f7a0de86ddb153a0d77ad7046aac1052 # v3.0.1
      with:
        lighthouseCheckResults: ${{ steps.lighthouse.outputs.lighthouseCheckResults }}
        minAccessibilityScore: "100"
        minBestPracticesScore: "92"
        minPerformanceScore: "55"
        minProgressiveWebAppScore: "80"
        minSeoScore: "100"

    - name: Publish artifacts
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
      if: ${{ always() }}
      with:
        name: lighthouse
        path: ${{ github.workspace }}/artifacts/lighthouse
        if-no-files-found: ignore
