name: lighthouse

on:
  pull_request:
    branches:
      - main
      - dotnet-vnext
      - dotnet-nightly
  workflow_dispatch:

permissions:
  contents: read

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_MULTILEVEL_LOOKUP: 0
  DOTNET_NOLOGO: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_SYSTEM_CONSOLE_ALLOW_ANSI_COLOR_REDIRECTION: 1
  NUGET_XMLDOC_MODE: skip
  TERM: xterm

jobs:
  lighthouse:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3

    - name: Start website
      shell: pwsh
      run: |
        Push-Location (Join-Path "src" "Website")
        npm ci
        npm run build
        Pop-Location
        Start-Process nohup 'dotnet run --project ./src/Website/Website.csproj --configuration Release'
        $StatusCode = 0
        $Attempts = 0
        While ($Attempts -lt 20) {
          $Response = Try {
            Invoke-WebRequest "https://localhost:5001" -SkipCertificateCheck
          } catch {
            $_.Exception.Response
          }
          $StatusCode = $Response.StatusCode
          If ($StatusCode -eq 200) {
            break
          }
          $Attempts++
          Start-Sleep -Seconds 5
        }
        If ($StatusCode -ne 200) {
          throw "Failed to successfully connect to website after $Attempts attempts."
        }
        New-Item -Path "${env:GITHUB_WORKSPACE}/artifacts/lighthouse" -ItemType Directory | Out-Null

    - name: Lighthouse
      uses: foo-software/lighthouse-check-action@v10.0.0
      id: lighthouse
      with:
        device: 'all'
        gitHubAccessToken: ${{ secrets.LIGHTHOUSE_ACCESS_TOKEN }}
        outputDirectory: ${{ github.workspace }}/artifacts/lighthouse
        prCommentEnabled: true
        urls: 'https://localhost:5001'
        wait: true

    - name: Check Lighthouse scores
      uses: foo-software/lighthouse-check-status-action@v2.0.1
      with:
        lighthouseCheckResults: ${{ steps.lighthouse.outputs.lighthouseCheckResults }}
        minAccessibilityScore: "100"
        minBestPracticesScore: "92"
        minPerformanceScore: "70"
        minProgressiveWebAppScore: "80"
        minSeoScore: "100"

    - name: Publish artifacts
      uses: actions/upload-artifact@v3
      if: ${{ always() }}
      with:
        name: lighthouse
        path: ${{ github.workspace }}/artifacts/lighthouse
        if-no-files-found: ignore
